<?php
/**
 * Implements hook_requirements().
 */
function yandex_checkout_requirements($phase) {
  $requirements = [];
  if ($phase == 'install' ) {
    if (!class_exists('\YandexCheckout\Client')) {
      $requirements['yandex_checkout_sdk_library'] = [
        'description' => t('Yandex Checkout requires the yandex-money/yandex-checkout-sdk-php library.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }

  return $requirements;
}
